export interface ICar {
  _id: string;
  name: string;
  userId: string;
  description: string;
  advertisementType: "Rent" | "Sale";
  price: number;
  paymentMethod: "Daily" | "Weekly" | "Monthly" | "Annually";
  mileage: number;
  speed: number;
  milesPerGallon: number;
  timestamp: string;
  year: number;
  transmission: string;
  fuel: string;
  bodyType: string;
  condition: string;
  engine: string;
  maintenance: string;
  currency: string;
  tags: string;
  imageUrl?: string;
  imageUrls?: string[];
  paymentId: string;
  visiblity: "Private" | "Public";
  status: "Pending" | "Active";
  createdAt?: Date;
  updatedAt?: Date;
  seller?: import("@/lib/seller-preview").SellerPreview;
}
