import type { FilterOption } from "@/components/filter-section";

export const HOUSE_FILTER_OPTIONS: FilterOption[] = [
  { value: "House", label: "House", category: "houseType" },
  { value: "Apartment", label: "Apartment", category: "houseType" },
  { value: "Guest House", label: "Guest House", category: "houseType" },
  { value: "1", label: "1 Bedroom", category: "bedroom" },
  { value: "2", label: "2 Bedrooms", category: "bedroom" },
  { value: "3", label: "3 Bedrooms", category: "bedroom" },
  { value: "4+", label: "4+ Bedrooms", category: "bedroom" },
  { value: "1", label: "1 Bathroom", category: "bathroom" },
  { value: "2", label: "2 Bathrooms", category: "bathroom" },
  { value: "3+", label: "3+ Bathrooms", category: "bathroom" },
  { value: "0-100", label: "0-100 sqm", category: "size" },
  { value: "100-200", label: "100-200 sqm", category: "size" },
  { value: "200-300", label: "200-300 sqm", category: "size" },
  { value: "300+", label: "300+ sqm", category: "size" },
  { value: "0-1000", label: "0-1,000", category: "price" },
  { value: "1000-5000", label: "1,000-5,000", category: "price" },
  { value: "5000-10000", label: "5,000-10,000", category: "price" },
  { value: "10000+", label: "10,000+", category: "price" },
  { value: "WiFi", label: "WiFi", category: "essentials" },
  { value: "Furnished", label: "Furnished", category: "essentials" },
  { value: "Play Ground", label: "Play Ground", category: "essentials" },
  { value: "Living Area", label: "Living Area", category: "essentials" },
  { value: "Gym", label: "Gym", category: "essentials" },
  { value: "Outdoor", label: "Outdoor", category: "essentials" },
  { value: "Dining Area", label: "Dining Area", category: "essentials" },
  { value: "Jacuzzi", label: "Jacuzzi", category: "essentials" },
  { value: "Steam", label: "Steam", category: "essentials" },
];
